name: build-deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      id-token: write

    env:
      OCTOPUS_SPACE: "Default"

    steps:
      - name: Checkout the code
        id: checkout
        uses: actions/checkout@v4

      - name: Build static site
        id: building
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
          bundler-cache: true
      - run: bundle exec middleman build --clean --verbose

      - name: Login to Octopus
        uses: OctopusDeploy/login@v1
        with:
          server: ${{ secrets.OCTOPUS_SERVER_URL }}
          service_account_id: ${{ secrets.OCTOPUS_SERVICE_ACCOUNT }}

      - name: Create a Zip package
        uses: OctopusDeploy/create-zip-package-action@v3
        with:
          package_id: "api-docs"
          version: "0.0.4"
          output_folder: "./packages/"
          base_path: "./build/"
          files: |
            **/*.*

      - name: Push a package to Octopus
        uses: OctopusDeploy/push-package-action@v3
        with:
          packages: |
            packages/**/*.zip

      - name: Use the package
        uses: OctopusDeploy/create-release-action@v3
        with:
          project: "docs-api"
          packages: |
            api-docs:.0.0.4
